### PR TITLE
Implement subdependency vendoring

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
You use it like this:

```ruby
desc "Vendor a specific version of net-http-persistent"
Automatiek::RakeTask.new("net-http-persistent") do |lib|
  lib.download = { :github => "https://github.com/drbrain/net-http-persistent" }
  lib.namespace = "Net::HTTP::Persistent"
  lib.prefix = "Bundler::Persistent"
  lib.vendor_lib = "lib/bundler/vendor/net-http-persistent"

  lib.dependency("connection_pool") do |sublib|
    sublib.version = "v2.2.2"
    sublib.download = { :github => "https://github.com/mperham/connection_pool" }
    sublib.namespace = "ConnectionPool"
    sublib.prefix = "Bundler"
    sublib.vendor_lib = "lib/bundler/vendor/connection_pool"
  end
end
```

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@segiddins Do you think you will find some time to have a look at this in the near future? Thank you :)

**Comment by deivid-rodriguez** [comment]
Thanks so much @segiddins!

If you could release 0.3.0 with this change, it'd be great. No pressure, of course :smiley:.

**Comment by deivid-rodriguez** [comment]
Also, if I get permissions, I don't mind releasing this myself :)

**Comment by segiddins** [comment]
0.3.0 released

**Comment by deivid-rodriguez** [comment]
Thank you! :heart:

**Pull request merged**
