### PR TITLE
Substitution improvements

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
With these changes, I can vendor the `uri` gem into `bundler` without needing any manual edits.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Hi @segiddins! Do you have some time to have a look at this? :)

**Comment by segiddins** [comment]
I'm having a hard time understanding what the implications of this change are

**Comment by deivid-rodriguez** [comment]
Can you elaborate? Do you refer to a specific commit?

**Comment by deivid-rodriguez** [comment]
I'm now bumping vendored URI and getting bit by this again getting a lot of changes in the vendored code (and thus having to undo them manually). Most (if not all) would've been prevented by this PR.

**Comment by deivid-rodriguez** [comment]
Thanks so much @segiddins!

**Pull request merged**
